<?php
// some helpers
$_helper = $this->helper('catalog/output');
// $storeId = Mage::app()->getStore()->getId();
$storeId = 3;
$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);

$skuList = array('PT00100', 'PT00101', 'PT00113', 'PT00199');
$collection = Mage::getModel('catalog/product')
->getCollection()
->addAttributeToFilter('sku', array('in' => $skuList));
 

// if no products are currently featured, display some text
if (!$collection->count()) :
 ?>
<?php else : ?>
  <div   class="grande">
      <?php
      $_collectionSize = $collection->count();
      foreach ($collection as $_product) :
        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
        ?>
      <div class="item">
          <center>
            <div class="item-image" style="">
              <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class=""><img class="lol-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150); ?>" width="150" height="150" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            </div>
            <div class="item-title" style="width:100%; height:auto;">
              <h2 class="product-name-slider"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            </div>
          </center>
        </div>
    <?php endforeach ?>
    </div>
 
  <?php endif ?>
